---
title: "Conclusion"
sidebar: true
toc: false
format:
  html:
    code-fold: show
    code-tools: false
---

## Summary

Now that we've seen all the graphs, we can come to a conclusion about the question 'Is classical music boring?'. In the Energy plot, Taylor Swift was a significantly higher energy level, and Bach was quite low. But, Bach had more keys, such as D minor, F# minor, G# minor, and D# minor, making it more interesting. With the Length plot, Taylor Swift was longer than the average length of music today, while Bach was shorter by almost 2 minutes. In the Valence plot, we saw that Bach was much happier, the points went to the very top, while Taylor Swift had a correlated x and y, and a wider range of tempo.
---

## Conclusion

Classical music is not boring! It may seem long and boring, but it is happier and has a wider range of keys than popular music. Popular music is written very simply, always sticking to the same keys, while classical music has more freedom. Popular music has always catered to listeners and streaming services, but they did not have streaming services when classical music was at it's boom, all they had was live performances. But classical (specifically baroque, which is when Bach was alive) music is more open to improvisation, so you can hear the performer's style of playing in the music. Classical music is interesting!

::: {.callout-tip}
## Did you know?
Did you know that there are different types of classical music? They are:

- Renaissance 
  – 1400-1600.
- Baroque 
  – 1600-1750.
- Classical 
  – 1750-1830.
- Romantic 
  – 1830-1900.
:::









