---
title: "Discovery Through the Arts - HUM110"
subtitle: "Winter 2026"
format: html
---

# Course Information
This course is Discovery and Discernment Through the Arts, offered at Brigham Young University Idaho. In the course I learned about the basic elements of visual art, music, literature, theatre, and film.

## Projects
### Greek Creation Story

I made a piece of art summarizing the Ancient Greek creation story, wrote a summary, and compared it to other creation stories, and how the story was affected by the environment and customs in Ancient Greece.

{{< pdf hum110/AssignmentCreationStory.pdf width=600 height=600 >}}

### Midterm Portfolio

In week 6 of the semester, I made a presentation analyzing various works of art, and debating whether or not they could be defined as beautiful. I analyzed 4 pieces of visual art, as well as 4 songs.

{{< pdf hum110/W06-Midterm-PortfolioHUM110.pdf width=600 height=370 >}}

### Final Portfolio

As the semester came to a close, I finished my biggest project yet. It was a summary of everything learned over the semester. I presented 2 works of art and why I found them beautiful, 5 pieces of classical music, 3 books, and I included future life plans and a reflection of what beauty means in the humanities.

{{< pdf hum110/W13-Portfolio-HUM110.pdf width=600 height=370 >}}
