---
title: "Binomial Theorem"
format: html
subtitle: "Quick Explaination"
date: "2025-09-29"
categories: [math]
---

## The Equation

The Binomial Theorem is one way to expand binomials without FOIL-ing. It works best when the binomial is raised to a higher degree, but the basic formula is:

$$
(a+b)^n = \sum_{k=0}^{n}\binom{n}{k} a^{n-k} b^k
$$

Where $\binom{n}{k}$ is defined as

$$\frac{n!}{k!(n-k)!}$$

Ok, so that looks like a lot! Let's take it section by section.

### The Breakdown

The binomial is $(a+b)^n$. That's a standard binomial.

The standard binomial would usually be expanded as $a^n+2ab+b^n$, but what if it was raised to the 10th, 20th, or 50th power?! That would be a lot of FOIL-ing, and it would get really hard to keep track of all the numbers! With the binomial theorem, we expand a little differently. The first half of the expansion is the sum of $n$ choose $k$, for some $n$, with values of $k$ starting at zero. That looks like this:

$$\sum_{k=0}^{n}\binom{n}{k}$$

The numbers $\binom{n}{k}$ are also called binomial coefficients, and we will see why later in this post. The second half of the expansion is $a^{n-k} b^k$.

We're going to keep the theorem in this broken up state for the post, because I find it easier to work with that way. You can use the whole theorem at once if you want, this is just what I do.

## Solving Problems
### 2nd degree binomial

We are going to start with a standard binomial, so you can see the theorem in action. We'll also expand using FOIL, just to double check that it's correct.

$(a+b)^2$

In this problem, $n$ is equal to $2$. We will get three different binomial coefficient numbers ($\binom{n}{k}$). Looking at our formula for $n$ choose $k$, we know that these three are:
$$\binom{2}{0}=\frac{2!}{0!(2-0)!}$$

$$\binom{2}{1}=\frac{2!}{1!(2-1)!}$$
$$\binom{2}{2}=\frac{2!}{2!(2-2)!}$$
So now, we solve the factorials to get our coefficient. The first one is equal to $1$, the second one is equal to $2$, and the third is equal to $1$.

:::{.callout-tip icon=false}
## $0!$?
$0!$ is equal to $1$, because there is exactly one way to order a group of zero numbers.
:::

That's the first part of the theorem, now we need to apply it to the second part:
$$
a^{n-k}b^k
$$
We know the value of $n$, and we know the values of $k$ ($0$, $1$, and $2$), so now we just need to plug them in. For $k=0$, this part of the equation will only be equal to $a^2$. We are subtracting nothing from the $n$, and $b$ is raised to no powers. When $k=1$, it will be equal to $ab$, and when $k=2$, it is only equal to $b$. However, our final expansion is **NOT** $a^2+ab+b^2$. We are missing the first half of the equation, and we need to apply our binomial coefficient numbers we found. When we apply the coefficients, it looks like this:

$$
\begin{aligned}
\binom{2}{0}&=1
\\\
a^{2-0}b^0&=a^2
\\\
\binom{2}{1}&=2
\\\
a^{2-1}b^1&=2ab
\\\
\binom{2}{2}&=1
\\\
a^{2-2}b^2=a^0b^2&=b^2
\end{aligned}
$$
This makes the full expansion of the binomial $(a+b)^2$
$$
a^2+2ab+b^2
$$
The FOIL method produces the same results:
$$
\begin{aligned}
(a+b)^2 &= (a+b)(a+b)
\\\
a(a+b) &= a^2+ab
\\\
b(a+b) &= b^2+ab
\\\
a^2+ab+ab+b^2 &=
a^2+2ab+b^2
\end{aligned}
$$
While both ways seem about the same when raised to the 2nd power, when we started raising more and more, the binomial theorem method will become a very useful tool. Even for powers of 3 or 4, FOIL-ing can get a little bit annoying.

### 3rd degree binomial

When higher degrees and more coefficients were introduced, I very possibly cried, so I hope to avoid that here!

Let's tackle the binomial
$$
(3a-b)^3
$$
I'll be FOIL-ing at the end of this section, but first, we will use the binomial theorem to do the expansion of this. We have our $n$, and we know where to start with $k$, so we can dive right in!

First, we need to do the sum of $\binom{3}{k}$ with values of $k$ ranging from $0$ to $3$. That will look like this:

$$\binom{3}{0}=\frac{3!}{0!(3-0)!}$$

$$\binom{3}{1}=\frac{3!}{1!(3-1)!}$$
$$\binom{3}{2}=\frac{3!}{2!(3-2)!}$$
$$\binom{3}{3}=\frac{3!}{3!(3-3)!}$$
We know we will have 4 coefficients. The first is $1$, the second is $3$, the third is $3$, and the fourth is $1$. But we need to remember that we are *NOT* done. We need to add the second part of the equation, and then re-apply the coefficients (unless you did the entire thing at once).

Our $n$ is $3$, and we have our values of $k$ ranging from $0$ to $3$, and all four of our coefficients. 

$$
\begin{aligned}
\binom{3}{0}&=1
\\\
3a^{3-0}b^0&=27a^3
\\\
\binom{3}{1}&=3
\\\
3a^{3-1}*-b^1&=-27a^2b
\end{aligned}
$$
Because $b$ is negative, we have to pay special attention to the signs we use.

$$
\begin{aligned}
\binom{3}{2}&=3
\\\
3a^{3-2}*-b^2&=9ab^2
\\\
\binom{3}{3}&=1
\\\
3a^{3-3}*-b^3&=-b^3
\end{aligned}
$$
Fully expanded, it will look like this:

$$
27a^3-27a^2b+9ab^2-b^3
$$
With FOIL, we get the same results.

$$(3a-b)^3=(3a-b)(3a-b)(3a-b)$$
$$
\begin{aligned}
(3a-b)(3a-b)=9a^2-6ab+b^2&=
\\\
(3a-b)9a^2-6ab+b^2 &=
\\\
27a^3-18a^2b+3ab^2-9a^2b+6ab^2-b^3&=
\\\
27a^3-27a^2b+9ab^2-b^3
\end{aligned}
$$

Now, it may look like FOIL is faster, but this is FOIL typed out, *after* I did it entirely by hand! Even for binomials raised to the third degree, the binomial theorem makes expansion much faster.

### 10th degree binomial

This is the last example problem for the more algebraic side of things, and I will not be FOIL-ing at the end for obvious reasons (I'm not about to do that much multiplication).

Let's take the problem

$$
(x+y)^{10}
$$
We have all the values needed for the binomial theorem, so now we will solve for the first half,

$$
\sum_{k=0}^{10}\binom{10}{k}
$$

::: {.callout-note collapse="true"}
## All solutions for $\sum_{k=0}^{10}\binom{10}{k}$

$$
\begin{aligned}
\binom{10}{0}&=\qquad\frac{10!}{0!(10-0)!}=&1
\\\
\binom{10}{1}&=\qquad\frac{10!}{1!(10-1)!}=&10
\\\
\binom{10}{2}&=\qquad\frac{10!}{2!(10-2)!}=&45
\\\
\binom{10}{3}&=\qquad\frac{10!}{3!(10-3)!}=&120
\\\
\binom{10}{4}&=\qquad\frac{10!}{4!(10-4)!}=&210
\\\
\binom{10}{5}&=\qquad\frac{10!}{5!(10-5)!}=&252
\\\
\binom{10}{6}&=\qquad\frac{10!}{6!(10-6)!}=&210
\\\
\binom{10}{7}&=\qquad\frac{10!}{7!(10-7)!}=&120
\\\
\binom{10}{8}&=\qquad\frac{10!}{8!(10-8)!}=&45
\\\
\binom{10}{9}&=\qquad\frac{10!}{9!(10-9)!}=&10
\\\
\binom{10}{10}&=\qquad\frac{10!}{10!(10-10)!}=&1
\end{aligned}
$$
:::

Now, we have our coefficients, and we can apply the second half of the theorem.

::: {.callout-note collapse="true"}
## Second half of theorem with coefficients $\binom{10}{k}$

$$
\begin{aligned}
x^{10-0}y^0 &=x^{10}
\\\
x^{10-1}y^1&=10x^9y
\\\
x^{10-2}y^2&=45x^8y^2
\\\
x^{10-3}y^3&=120x^7y^3
\\\
x^{10-4}y^4&=210x^6y^4
\\\
x^{10-5}y^5&=252x^5y^5
\\\
x^{10-6}y^6&=210x^4y^6
\\\
x^{10-7}y^7&=120x^3y^7
\\\
x^{10-8}y^8&=45x^2y^8
\\\
x^{10-9}y^9&=10xy^9
\\\
x^{10-10}y^10&=y^{10}
\end{aligned}
$$
:::

*SO*, fully expanded, its going to be one very large equation, which is why using the binomial theorem is better, so you don't get tangled up in a bunch of multiplication.

$$
x^{10}+10x^9y+45x^8y^2+120x^7y^3+210x^6y^4+252x^5y^5+210x^4y^6+120x^3y^7+45x^2y^8+10xy^9+y^{10}
$$

The Binomial Theorem offers a faster way to expand binomials raised to higher degrees, and is a really important theorem to understand.